### ISSUE TITLE
It keeps adding devices

### ISSUE THREAD

**Issue by giejay** [thijsdebets/networkdetectz#3]
Hi, 

every now and then I have to clear all new devices again in my domoticz because it adds 20somewhat devices... Can I prevent it from adding devices at all? My two users (myself and my gf) are configured so I don't need any new devices. In the previous version I would clear the nwd.log and it wouldnt add any new devices but it doesnt seem to use this file anymore in the new version...

**Comment by thijsdebets** [comment]
I would lov to know why it keeps adding devices as if they were new, but for now I added the AutoAdd option in the config file. If you do a new pull, run once and edit the nwd-config.own file and change the AutoAdd setting to any value other then YES, it will stop looking for newly detected devices, and so will also stop adding them to Domoticz. Does this help?

**Comment by giejay** [comment]
Well I am removing the devices again from Domoticz so perhaps the script will add them again?

I pulled and edited the AutoAdd, lets see if t works:) Thank you for the very fast response and fix!

**Comment by thijsdebets** [comment]
Ah, yes, it will add all devices that are detected in the network. I thought it added doublures, but what I think is normal behaviour. Hope this new option suits your requirements.
